# Generated by Django 4.2.5 on 2023-09-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id_ciudad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_departamento', models.IntegerField(blank=True, null=True)),
                ('nombre_departamento', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_hora_crear', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_modificar', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_documento', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.IntegerField(blank=True, null=True)),
                ('nombres_empleado', models.CharField(blank=True, max_length=30, null=True)),
                ('apellidos_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_crear', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_modificar', models.DateTimeField(auto_now=True)),
                ('id_ciudad_fk', models.ForeignKey(db_column='id_ciudad_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='api.ciudades')),
                ('id_departamento_fk', models.ForeignKey(db_column='id_departamento_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='api.departamentos')),
                ('id_tipo_documento_fk', models.ForeignKey(db_column='id_tipo_documento_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='api.tipodocumento')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.AddField(
            model_name='ciudades',
            name='id_departamento_fk',
            field=models.ForeignKey(db_column='id_departamento_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='api.departamentos'),
        ),
    ]
