# Generated by Django 4.2.5 on 2023-09-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_departamento', models.IntegerField(blank=True, null=True)),
                ('nombre_departamento', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_hora_crear', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_modificar', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.IntegerField(blank=True, null=True)),
                ('nombres_empleado', models.CharField(blank=True, max_length=30, null=True)),
                ('apellidos_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_crear', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_modificar', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('tipo_documento', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
    ]
