# Generated by Django 4.2.4 on 2023-09-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ciudades',
                'managed': False,
            },
        ),
    ]
