# Generated by Django 4.2.5 on 2023-09-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_permiso', models.CharField(max_length=300)),
                ('codename', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
    ]
