# Generated by Django 4.2.5 on 2023-09-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ciudades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudades',
            options={},
        ),
        migrations.AlterModelOptions(
            name='departamentos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={},
        ),
    ]
